### ISSUE TITLE
I'm not seeing my mounted partitions

### ISSUE THREAD

**Issue by dennisTGC** [SergKolo/udisks-indicator#5]
If i look at the readme.md, it shows your mounted partitions from the tray icon. But i can't see my mounted partitions. Could it be because i'm on a NVME disk?

It does see the disk though in the disks utility.

**Comment by SergKolo** [comment]
@Fr3llD  Curious issue. Are your partitions encrypted ? Can you do `sudo blkid` command and let me know if you see it mention LUKS ? Can you see the USB disks being mounted ?  Also, can you provide a screenshot of what does appear on the indicator ?

**Comment by dennisTGC** [comment]
I can see the SATA disk in my workstation, but not the NVMe disk. The disks aren't encrypted, although the ubuntu home dir is encrypted. USB sticks are shown aswell. I really think it's the NVMe's, because the same is happening on my Dell XPS13 laptop (im now on a Dell T3420).

$ sudo blkid
/dev/nvme0n1p5: UUID="f080bb37-838a-40eb-9fdf-747b017f9212" TYPE="ext4" PARTUUID="2c555996-56e3-459d-8946-adff25bdced2"
/dev/dm-0: UUID="00431f34-7945-43cd-bc04-ba7c69e13ad6" TYPE="swap"
/dev/nvme0n1p1: LABEL="ESP" UUID="FE8F-66EF" TYPE="vfat" PARTUUID="2b3399f3-091b-11e6-8905-eaf41e34f4f6"
/dev/nvme0n1p4: LABEL="WINRETOOLS" UUID="A646BD8846BD5A2F" TYPE="ntfs" PARTUUID="2b3399f5-091b-11e6-8905-eaf41e34f4f6"
/dev/sda1: LABEL="Data" UUID="064eee53-8025-4b33-bc1b-65c9ac9955c5" TYPE="ext4" PARTLABEL="Data" PARTUUID="9a06ab77-eb5e-4f1e-9780-a99562f5a513"
/dev/sda2: LABEL="Data" UUID="405E08CB5E08BC22" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="5c82fc57-d35c-4ca9-970d-86cd1d0cf5a6"
/dev/nvme0n1: PTUUID="4fbbe750-5fa9-46a4-9d69-d703c704b6ec" PTTYPE="gpt"
/dev/nvme0n1p2: PARTUUID="2b3399f4-091b-11e6-8905-eaf41e34f4f6"
/dev/nvme0n1p3: PARTUUID="92e13e27-968e-4d98-8dca-2baf0e40ecc2"

**Comment by dennisTGC** [comment]
I think you fixed it? I can see my NVMe drives now!

**Comment by SergKolo** [comment]
@Fr3llD  I've committed a few changes , which deal with unintended errors, but I didn't target NVMe drives specifically. I suppose  the issue was related to one of those errors and not drives themselves.  In any case, I'm happy it works for you now :) I'll close the bug report for now, since it went away, but feel free to let me know if the issue reoccurs
