### ISSUE TITLE
closes after about 2 seconds

### ISSUE THREAD

**Issue by elswerky** [SergKolo/udisks-indicator#7]
hello SergoKolo
thx for this indicator 
i have a bug which is the indicator closes in system tray after about 2 seconds 
i used  it in deepin os

**Comment by SergKolo** [comment]
@elswerky Well, luckily for you I am now using Deepin 15.5, and I'll look into this issue. Allow me some time, maybe couple weeks. Btw, just curious are you Chinese user of Deepin ?

**Comment by elswerky** [comment]
no iam no Chinese
am egyptian
but i am in testing group if you want to be im contact with deepin team on telegram i can help

also as you know deepin already provide hard partitions indicator in dock but it doesn't show home partition if you have /home in seperate partition so i looked for your tool as it is useful and small in size (9 kb)

**Comment by SergKolo** [comment]
@elswerky  OK, very well. I've cloned the repo into my Deepin, so far seems to work fine, except for opening Disks utility ( by default Deepin doesn't have Gnome Disks ).  Try to run the indicator via terminal, let me know what errors does it throw, and what happens on command-line during the crash.

**Comment by elswerky** [comment]
ok
now i am away from pc and it won't be accessible for some hours,, you can join deepin group on telegram
https://telegram.me/deepin
and you can contact me there on telegram on this ID 
https://t.me/elswerky

**Comment by elswerky** [comment]
@SergKolo  ok where is the files you said you cloned into deepin ???

**Comment by SergKolo** [comment]
@elswerky I cloned the repository into my Deepin 15.5 , I think you misunderstood what I said. Indication works on my system without issues. Like I said before, run it from terminal and let me know what errors show up there

**Comment by elswerky** [comment]
@SergKolo  ok i unistalled v 1 and installed a deb of v2 and found this bug fixed ,,, i think it was a bug in v 1

**Comment by elswerky** [comment]
i   will close this issue
